Given /^a model with a thumbnail variation$/ do
  class Image < CouchRest::Model::Base
    use_database IMAGE_DB
    include CouchPhoto

    override_id! 

    variations do
      thumbnail "50x50"
    end
  end
end

When /^I create an instance of that model with an image file$/ do
  @image = Image.new
  file = 
  @image.original "features/setup/fixtures/avatar.jpg"
  @image.save
end

Then /^I should have an autogenerated image thumbnail with my instance$/ do
  @image.has_attachment?("original.jpg").should be_true
  @image.has_attachment?("variations/thumbnail.jpg").should be_true
end
