Given /^a model with a thumbnail variation$/ do
  class Image < CouchRest::Model::Base
    use_database IMAGE_DB
    include CouchPhoto

    override_id! 

    variations do
      thumbnail "50x50"
    end
  end
end

When /^I create an instance of that model with an image file$/ do
  @image = Image.new
  @image.original = "features/setup/fixtures/avatar.jpg"
  @image.save
end

Then /^I should have an autogenerated image thumbnail with my instance$/ do
  @image.has_attachment?("original.jpg").should be_true
  @image.has_attachment?("variations/thumbnail.jpg").should be_true
end

Given /^an instance of a model CouchPhotoImage that includes CouchPhoto and has an original image "([^"]*)"$/ do |image|
  class CouchPhotoImage < CouchRest::Model::Base
    use_database IMAGE_DB
    include CouchPhoto
  end
  
  @image = CouchPhotoImage.new
  @image.original = "features/setup/fixtures/#{image}"
  @image.save
end

When /^I call the "add_variation" method on the instance with "([^"]*)" and "([^"]*)"$/ do |variation, image|
  @image.add_variation "#{variation}", @image.original.data
end

Then /^my image should have a variation called "([^"]*)"$/ do |image|
  @variations = @image.variations
  @variations.each do |variation|
    ["#{image}"].include?(variation.name).should be_true
  end
end

Then /^it should be accessible from "([^"]*)"$/ do |arg1|
  @variations.each do |variation|
    variation.url.should == [IMAGE_DB.to_s, @image.id, variation.filename].join("/")
  end
end

