Feature: Image Variations
  As a developer
  I want to tell my Image model to generate image variations
  So that all my images can have auto-generated variations

  Scenario: Auto generated thumbnails
    Given a model with a thumbnail variation
    When I create an instance of that model with an image file
    Then I should have an autogenerated image thumbnail with my instance

  @focus
  Scenario: Creating custom (non-auto-generated) variations
    Given an instance of a model CouchPhotoImage that includes CouchPhoto and has an original image "avatar.jpg"
    When I call the "add_variation" method on the instance with "awesome_variations/my_variation.jpg" and "avatar.jpg"
    Then my image should have a variation called "awesome_variations/my_variation.jpg"
    And it should be accessible from "avatar.jpg/variations/awesome_variations/my_variation.jpg"