Feature: Image Variations
  As a developer
  I want to tell my Image model to generate image variations
  So that all my images can have auto-generated variations

  Scenario: Auto generated thumbnails
    Given a model with a thumbnail variation
    When I create an instance of that model with an image file
    Then I should have an autogenerated image thumbnail with my instance

  Scenario: Creating a custom variation
    Given an instance of an Image model that includes CouchRest:
      """
        class Image < CouchRest::Model::Base
          use_database IMAGE_DB
          include CouchPhoto
          override_id! 
        end

        @image = Image.new
        @image.original = "features/setup/fixtures/avatar.jpg"
        @image.save
      """

    When I add a custom variation to it using the ":file =>" qualifier and save:
      """
        @image.add_variation "my_custom_variation.jpg", :file => "features/setup/fixtures/avatar.jpg"
        @image.save
      """

    Then my image should have a custom variation with that name:
      """
        @image.variation("my_custom_variation.jpg").data.should == File.read("features/setup/fixtures/avatar.jpg")
      """

    When I add a custom variation to it using the ":blob =>" qualifier and save:
      """
        @image.add_variation "blob_variation.jpg", :blob => File.read("features/setup/fixtures/avatar.jpg")
        @image.save
      """

    Then my image should have a custom variation with that name:
      """
        @image.variation("blob_variation.jpg").data.should == File.read("features/setup/fixtures/avatar.jpg")
      """